// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231017134858_ProductSeeding")]
    partial class ProductSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Neste livro você encontra 1.001 questões – 900 de provas passadas e 101 novas – para praticar e testar seus conhecimentos.",
                            ImageUrl = "https://m.media-amazon.com/images/I/71LwLOXe6aL._SY466_.jpg",
                            ProductPrice = 75.98m,
                            Title = "1001 Questões para Fazer Antes de Passar no ENEM Espiral"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Passar em uma boa universidade é o sonho de muitos, mas o vestibular tende a ser um momento cheio de tensão e nervosismo para os alunos.",
                            ImageUrl = "https://m.media-amazon.com/images/I/81cbf9eKBBL._SY466_.jpg",
                            ProductPrice = 34.98m,
                            Title = "Redação infalível: E outras dicas para você arrasar nas provas"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Neste livro, inédito no Brasil, você vai descobrir, após 75 anos de segredo, por meio dessa entrevista exclusiva que Napoleon Hill fez, quebrando o código secreto da mente do Diabo.",
                            ImageUrl = "https://m.media-amazon.com/images/I/819ERrDHRcL._SY466_.jpg",
                            ProductPrice = 25.90m,
                            Title = "Mais esperto que o Diabo: O mistério revelado da liberdade e do sucesso"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
